printWidth: 140
wrapAttributes: true
tabWidth: 2
useTabs: false
semi: true
singleQuote: true
quoteProps: 'consistent'
jsxSingleQuote: true
trailingComma: 'all'
bracketSpacing: true
bracketSameLine: false
arrowParens: 'always'
requirePragma: false
endOfLine: 'lf'
singleAttributePerLine: true
