arrowParens: 'always'
bracketSpacing: true
bracketSameLine: false
endOfLine: 'lf'
jsxSingleQuote: true
printWidth: 140
quoteProps: 'consistent'
requirePragma: false
semi: true
singleAttributePerLine: true
singleQuote: true
tabWidth: 2
trailingComma: 'all'
useTabs: false
wrapAttributes: true
plugins: ['prettier-plugin-tailwindcss']
