version: '3.8'

services:
  db-psql:
    image: daigaku-psql-image
    container_name: daigaku-psql-container
    hostname: db-psql
    build:
      context: ./database/psql
      dockerfile: Dockerfile
    environment:
      POSTGRES_DB: ${POSTGRES_DATABASE}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - 5432:5432
    expose:
      - 5432
    networks:
      - daigaku
    restart: always


  db-redis:
    image: daigaku-redis-image
    container_name: daigaku-redis-container
    build:
      context: ./database/redis-cache
      dockerfile: Dockerfile
    ports:
      - 6379:6379
    expose:
      - 6379
    networks:
      - daigaku
    restart: unless-stopped


  backend-rabbitmq-mgmt:
    image: daigaku-rabbitmq-mgmt-image
    container_name: daigaku-rabbitmq-mgmt-container
    build:
      context: ./backend/rabbitmq-mgmt
      dockerfile: Dockerfile
    hostname: ${RABBITMQ_HOST}
    ports:
      - 5672:5672
      - 15672:15672
    expose:
      - 5672
      - 15672
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    networks:
      - daigaku


  backend-s3:
    image: daigaku-s3-image
    container_name: daigaku-s3-container
    build:
      context: ./backend/s3
      dockerfile: Dockerfile
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION}
      AMAZON_BUCKET: ${AMAZON_BUCKET}
      AMAZON_ENDPOINT_URL: ${AMAZON_ENDPOINT_URL}
      SPRING_RABBITMQ_HOST: ${RABBITMQ_HOST}
    ports:
      - 8081:8081
    expose:
      - 8081
    networks:
      - daigaku


  backend-email:
    image: daigaku-email-image
    container_name: daigaku-email-container
    build:
      context: ./backend/email
      dockerfile: Dockerfile
    environment:
      JAVAMAIL_HOST: ${JAVAMAIL_HOST}
      JAVAMAIL_PORT: ${JAVAMAIL_PORT}
      JAVAMAIL_USER: ${JAVAMAIL_USER}
      JAVAMAIL_PASSWORD: ${JAVAMAIL_PASSWORD}
      SPRING_RABBITMQ_HOST: ${RABBITMQ_HOST}
    ports:
      - 8082:8082
    expose:
      - 8082
    networks:
      - daigaku


  backend-core:
    image: daigaku-core-image
    container_name: daigaku-core-container
    build:
      context: ./backend/core
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://${POSTGRES_SERVICE}/${POSTGRES_DATABASE}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      SPRING_DATA_REDIS_HOST: ${REDIS_CONTAINER}
      SPRING_RABBITMQ_HOST: ${RABBITMQ_HOST}
    ports:
      - 8080:8080
    expose:
      - 8080
    networks:
      - daigaku
    depends_on:
      - db-psql
      - db-redis
      - backend-rabbitmq-mgmt
      - backend-s3
      - backend-email


  frontend:
    image: daigaku-frontend-image
    container_name: daigaku-frontend-container
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 80:80
    expose:
      - 80
    networks:
      - daigaku
    depends_on:
      - backend-core


volumes:
  db-psql:
    driver: local
  db-redis:
    driver: local
  backend-rabbitmq-mgmt:
    driver: local


networks:
  daigaku:
    driver: bridge