name: install npm
description: install npm and dependencies

inputs:
  cache-dependency-path:
    description: path to lockfile for npm caching
    required: true
    default: 'frontend/package-lock.json'

  working-directory:
    description: Working directory to run npm commands
    required: true
    default: 'frontend'

runs:
  using: composite

  steps:
      - name: install NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
          cache-dependency-path: ${{ inputs.cache-dependency-path }}

      - name: install dependencies
        shell: bash
        working-directory: ${{ inputs.working-directory }}
        run: npm run dev:install