name: install npm
description: install npm and dependencies

runs:
  using: composite
  steps:
      - name: install NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
          cache-dependency-path: frontend/package-lock.json

      - name: install dependencies
        shell: bash
        working-directory: frontend
        run: npm run dev:install