name: install npm
description: install npm and dependencies utility action

parameters:
  cache-dependency-path:
    description: path to lockfile for npm caching
    required: true

  working-directory:
    description: Working directory to run npm commands
    required: true

runs:
  using: composite

  steps:
      - name: install NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
          cache-dependency-path: ${{ parameters.cache-dependency-path }}

      - name: install dependencies
        shell: bash
        working-directory: ${{ parameters.working-directory }}
        run: npm run dev:install