#  e2e-tests:
#    runs-on: ubuntu-latest
#    needs:
#      - backend-unit-tests
#
#    steps:
#      - uses: actions/checkout@v4
#
#      - name: install:node-lts
#        uses: actions/setup-node@v4
#        with:
#          node-version: lts/*
#
#      - name: install:frontend-dependencies
#        working-directory: ./frontend
#        run: |
#          npm run dev:install:clean
#
#      - name: install:playwright-dependencies
#        working-directory: ./frontend
#        run: |
#          npm run test:install
#
#      - name: configure:playwright-environment
#        run: |
#          echo "PLAYWRIGHT_STUDENT_EMAIL=${{ secrets.PLAYWRIGHT_STUDENT_EMAIL }}" >> $GITHUB_ENV
#          echo "PLAYWRIGHT_STUDENT_PASSWORD=${{ secrets.PLAYWRIGHT_STUDENT_PASSWORD }}" >> $GITHUB_ENV
#          echo "PLAYWRIGHT_STUDENT_AUTH_STATE_PATH=${{ secrets.PLAYWRIGHT_STUDENT_AUTH_STATE_PATH }}" >> $GITHUB_ENV
#
#      - name: run:playwright-tests
#        working-directory: ./frontend
#        run: |
#          npm run test:start
#
#      - name: run:test-report
#        uses: actions/upload-artifact@v4
#        if: always()
#        with:
#          name: playwright-report
#          path: ./frontend/playwright-report/index.html
#          retention-days: 1
#          overwrite: true