name: DaigakuSpringApplication Workflow

on:
  push:
    branches: 
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    - name: Configure DaigakuSpringApplication application.properties variables
      run: |
        cd backend
        cat >./src/main/resources/application.properties <<EOF
        spring.config.import=optional:file:.env[.properties]
        spring.datasource.url=jdbc:postgresql://localhost:5432/daigaku
        spring.datasource.username=postgres
        spring.datasource.password=admin
        spring.jpa.hibernate.ddl-auto=none
        spring.sql.init.mode=always
        spring.cache.type=redis
        spring.data.redis.host=localhost
        spring.data.redis.port=6379
        spring.datasource.driver-class-name=org.postgresql.Driver
        EOF
      
    - name: Build DaigakuSpringApplication with Maven
      run: |
        cd backend
        ./mvnw clean package

    - name: Test DaigakuSpringApplication
      run: |
        cd backend
        ./mvnw test
