name: DaigakuSpringApplication Workflow

on:
  push:
    branches: 
      - master
  pull_request:
    branches:
      - master

jobs:
  build-then-test:
    runs-on: ubuntu-latest

    services:
      db-psql:
        image: postgres:latest
        env:
          POSTGRES_DB: daigaku
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: admin
        ports:
          - 5432:5432
      db-redis:
        image: redis:latest
        ports:
          - 6379:6379

    steps:
      - uses: actions/checkout@v4
      
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
          
      - name: Build RabbitMQCommonLibSpringApplication with Maven
        run: |
          cd backend/common-libs/rabbitmq
          ./mvnw install package -DskipTests

      - name: Configure DaigakuSpringApplication application.properties variables
        run: |
          cd backend/core
          cat >./src/main/resources/application.properties <<EOF
          spring.config.import=optional:file:.env[.properties]
          spring.datasource.url=jdbc:postgresql://localhost:5432/daigaku
          spring.datasource.username=postgres
          spring.datasource.password=admin
          spring.cache.type=redis
          spring.data.redis.host=localhost
          spring.data.redis.port=6379
          spring.datasource.driver-class-name=org.postgresql.Driver
          tamasnovak.app.jwtSecret=fakeSecret
          tamasnovak.app.jwtExpirationMs=10000000
          EOF
        
      - name: Build DaigakuSpringApplication with Maven
        run: |
          cd backend/core
          ./mvnw clean package -DskipTests
  
      - name: Test DaigakuSpringApplication
        run: |
          cd backend/core
          ./mvnw test
