name: DaigakuSpringApplication Workflow


on:
  push:
    branches: 
      - master
      - githubactiontest
  pull_request:
    branches:
      - master


jobs:
  build-then-test:
    runs-on: ubuntu-latest
    defaults:
     run:
      working-directory: ./backend

    services:
      db-psql:
        image: postgres:latest
        env:
          POSTGRES_DB: daigaku
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: admin
        ports:
          - 5432:5432
      db-redis:
        image: redis:latest
        ports:
          - 6379:6379

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Install parent POM
        run: |
          mvn install -N

      - name: Build RabbitMQCommonLibSpringApplication
        run: |
          cd common-libs/rabbitmq
          mvn clean install -DskipTests
          mkdir staging && cp target/*.jar staging

      - name: Test RabbitMQCommonLibSpringApplication
        run: |
          cd common-libs/rabbitmq
          ./mvnw test


      - name: Set up a cache for Maven
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Persist workflow data as artifacts
        uses: actions/upload-artifact@v2
        with:
          name: github-actions-artifact
          path: staging

      - name: Configure DaigakuSpringApplication application.properties variables
        run: |
          cd core
          cat >./src/main/resources/application.properties <<EOF
          spring.config.import=optional:file:.env[.properties]
          spring.datasource.url=jdbc:postgresql://localhost:5432/daigaku
          spring.datasource.username=postgres
          spring.datasource.password=admin
          spring.cache.type=redis
          spring.data.redis.host=localhost
          spring.data.redis.port=6379
          spring.datasource.driver-class-name=org.postgresql.Driver
          tamasnovak.app.jwtSecret=fakeSecret
          tamasnovak.app.jwtExpirationMs=10000000
          EOF
        
      - name: Build DaigakuSpringApplication with Maven
        run: |
          cd core
          mvn clean install -DskipTests
  
      - name: Test DaigakuSpringApplication
        run: |
          cd core
          ./mvnw test
