name: e2e-build-and-test

on:
  push:
    branches:
      - "*"

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./backend

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: install parent pom.xml
        run: |
          mvn install -N

      - name: build and test RabbitMQModuleApplication
        run: |
          cd common-libs/rabbitmq
          mvn clean install

      - name: build and test DaigakuCoreApplication
        run: |
          cd core
          mvn clean install

      - name: Build and start backend and database
        run: |
          docker-compose -f docker-compose.playwright.yml up -d --build

  playwright-e2e-tests:
    runs-on: ubuntu-latest
    needs:
      - build-and-test

    steps:
      - uses: actions/checkout@v4

      - name: install:node-lts
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: install:playwright-dependencies-browsers
        working-directory: ./frontend
        run: |
          npm run test:install

      - name: run:playwright-tests
        working-directory: ./frontend
        run: |
          npm run test:start

      - name: Shutdown Docker Containers
        run: |
          docker-compose -f docker-compose.playwright.yml down

      # - name: run:test-report
      #   uses: actions/upload-artifact@v4
      #   if: always()
      #   with:
      #     name: playwright-report
      #     path: ./frontend/playwright-report/index.html
      #     retention-days: 1
      #     overwrite: true
