name: frontend playwright build-and-test e2e-tests workflow

on:
  push:
    branches:
      - "*"

jobs:
  playwright-e2e-tests:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.39.0-focal

    steps:
      - uses: actions/checkout@v4

      - name: install node lts
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: install java
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"

      - name: build core backend module
        working-directory: ./backend
        run: |
          mvn clean install -pl core -am -DskipTests

      - name: configure DaigakuCoreApplication application.properties variables
        run: |
          cd backend/core
          cat > src/main/resources/application.properties <<EOF
          spring.config.import=optional:file:.env[.properties]
          spring.datasource.url=jdbc:postgresql://localhost:5432/${{ secrets.POSTGRES_DB }}
          spring.datasource.username=${{ secrets.POSTGRES_USER }}
          spring.datasource.password=${{ secrets.POSTGRES_PASSWORD }}
          spring.cache.type=redis
          spring.data.redis.host=localhost
          spring.data.redis.port=6379
          spring.datasource.driver-class-name=org.postgresql.Driver
          tamasnovak.app.jwtSecret=fakeSecret
          tamasnovak.app.jwtExpirationMs=10000000
          EOF

      - name: start core backend module
        working-directory: ./backend/core
        run: |
          nohup mvn spring-boot:run &

      - name: install frontend dependencies
        run: |
          cd frontend
          npm install

      - name: install playwright browsers
        run: |
          cd frontend
          npx playwright install

      - name: run playwright tests
        run: |
          cd frontend
          npm run test

      - name: upload .html test report as artifact
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: ./frontend/playwright-report/index.html
          retention-days: 1
          overwrite: true
