name: playwright tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-then-test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./frontend

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - uses: actions/setup-java@v3
        with:
          java-version: "21"
          distribution: "temurin"

      - name: build Core backend module
        working-directory: ./backend/core
        run: |
          mvn clean install -pl core -am

      - name: start Core backend module
        working-directory: ./backend/core
        run: |
          nohup mvn spring-boot:run &

      - name: Install dependencies
        run: npm install

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Start the development server
        run: npm run dev &
        env:
          CI: true

      - name: Run Playwright tests
        run: |
          cd tests
          npx playwright test
