name: e2e-build-and-test

on:
  push:
    branches:
      - "*"

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: set up jdk 21
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"
          cache: maven

      - name: install parent pom.xml
        working-directory: ./backend
        run: mvn install -N

      - name: build and test RabbitMQModuleApplication
        working-directory: ./backend/common-libs/rabbitmq
        run: mvn clean install

      - name: build and test DaigakuCoreApplication
        working-directory: ./backend/core
        run: mvn clean install

      - name: Install Docker Compose
        run: |
          curl -L "https://github.com/docker/compose/releases/download/v2.17.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

      - name: Build and start backend and database
        run: docker-compose -f docker-compose.workflow.yml up -d --build

  playwright-e2e-tests:
    runs-on: ubuntu-latest
    needs:
      - build-and-test

    steps:
      - uses: actions/checkout@v4

      - name: install:node-lts
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: install:playwright-dependencies-browsers
        working-directory: ./frontend
        run: |
          npm run test:install

      - name: run:playwright-tests
        working-directory: ./frontend
        run: |
          npm run test:start

      - name: Shutdown Docker Containers
        run: |
          docker-compose -f docker-compose.workflow.yml down

      # - name: run:test-report
      #   uses: actions/upload-artifact@v4
      #   if: always()
      #   with:
      #     name: playwright-report
      #     path: ./frontend/playwright-report/index.html
      #     retention-days: 1
      #     overwrite: true
