name: unit-and-e2e-testing-workflow

on:
  push:
    branches:
      - "*"

jobs:
  backend-unit-tests:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./backend

    services:
      db-psql:
        image: postgres:17.2-alpine
        env:
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
        ports:
          - 5432:5432
      db-redis:
        image: redis:7.4.2-alpine
        ports:
          - 6379:6379

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: set up jdk 21
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"
          cache: maven

      - name: install:parent-pom.xml
        run: |
          mvn install -N

      - name: build-then-test:RabbitMQModuleApplication
        run: |
          cd common-libs/rabbitmq
          mvn clean install

      - name: configure:DaigakuCoreApplication
        run: |
          cd core
          cat > src/main/resources/application.yml <<EOF
          spring:
            datasource:
              url: jdbc:postgresql://db-psql:5432/${POSTGRES_DB}
              username: ${POSTGRES_USER}
              password: ${POSTGRES_PASSWORD}
              driver-class-name: org.postgresql.Driver
            data:
              redis:
                host: db-redis
                port: 6379
          EOF

      - name: build-then-test:DaigakuCoreApplication
        run: |
          cd core
          mvn clean install

  e2e-tests:
    runs-on: ubuntu-latest
    needs:
      - backend-unit-tests

    steps:
      - uses: actions/checkout@v4

      - name: install:node-lts
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: install:frontend-dependencies
        working-directory: ./frontend
        run: |
          npm run dev:install:clean

      - name: install:playwright-dependencies
        working-directory: ./frontend
        run: |
          npm run test:install

      - name: configure:playwright-environment
        run: |
          echo "PLAYWRIGHT_STUDENT_EMAIL=${{ secrets.PLAYWRIGHT_STUDENT_EMAIL }}" >> $GITHUB_ENV
          echo "PLAYWRIGHT_STUDENT_PASSWORD=${{ secrets.PLAYWRIGHT_STUDENT_PASSWORD }}" >> $GITHUB_ENV
          echo "PLAYWRIGHT_STUDENT_AUTH_STATE_PATH=${{ secrets.PLAYWRIGHT_STUDENT_AUTH_STATE_PATH }}" >> $GITHUB_ENV

      - name: run:playwright-tests
        working-directory: ./frontend
        run: |
          npm run test:start

      - name: run:test-report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: ./frontend/playwright-report/index.html
          retention-days: 1
          overwrite: true
